GET https://httpbin.org/ip

### helath check for user api
GET https://user-api.parking.davao.page/health

### API Actuator Health check
GET {{userActuatorBaseUrl}}/actuator/health

### Admin Actuator Health check
GET {{adminActuatorBaseUrl}}/actuator/health

### API Actuator Bean Check
GET {{userActuatorBaseUrl}}/actuator/beans

### Admin Actuator Bean Check
GET {{adminActuatorBaseUrl}}/actuator/beans

### API Actuator Flyway Check
GET {{userActuatorBaseUrl}}/actuator/flyway

### Admin Actuator Flyway Check
GET {{adminActuatorBaseUrl}}/actuator/flyway

