### User Login
POST {{address-admin}}/api/auth/login
X-XSRF-TOKEN: {{XSRF-TOKEN}}
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Get CSRF Token
GET {{address-admin}}/api/auth/get-csrf-token