### Get Parking Lot by ID
GET {{address-management}}/api/parking-lot/get/9eac93b7-0b7e-4eb0-86d6-9c002fb4c8c1
Authorization: Bearer {{token}}

### Get Parking Lots By Range
GET {{address-management}}/api/parking-lot/get-by-location?latitude=7.110451&longitude=125.633836&distance=0.1
Authorization: Bearer {{token}}

### Get my parking lots
GET {{address-management}}/api/parking-lot/get-mine
Authorization: Bearer {{token}}

### Create Parking Lot
POST {{address-management}}/api/parking-lot/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Parking Lot 1",
  "latitude": 7.110451,
  "longitude": 125.633836,
  "address": "Address 1",
  "description": "Description 1",
  "capacity": 10
}

### Update Parking Lot
PUT {{address-management}}/api/parking-lot/update/9772e5e5-3cca-4fa7-ad26-45823d638a4b
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Parking Lot 2",
  "rate": "11000.00",
  "capacity": 15,
  "latitude": 7.110451,
  "longitude": 125.633836
}