# AUTH APIs

### User Login
POST {{adminBaseUrl}}/api/auth/login
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Get CSRF Token
GET {{adminBaseUrl}}/api/auth/get-csrf-token

# USER APIs

### User Logout
POST {{adminBaseUrl}}/api/user/logout
Authorization: Bearer {{adminToken}}

### Test
GET {{adminBaseUrl}}/api/user/test
Authorization: Bearer {{adminToken}}

# DASHBOARD APIs

### Test Get URL
GET {{adminBaseUrl}}/api/dashboard/test
Authorization: Bearer {{adminToken}}