### User Login
POST {{adminBaseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Create Jeepney
POST {{adminBaseUrl}}/api/jeepney
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "jeepneyUuid": "string",
  "name": "Jeepney 1",
  "plateNumber": "ABC123",
  "drivers": "ttest",
  "capacity": 0,
  "latitude": 0.0,
  "longitude": 0.0,
  "status": 1,
  "flag": 0
}

### Get User Profile
GET {{adminBaseUrl}}/api/profile/me
Authorization: Bearer {{adminToken}}

### Get List of Users
GET {{adminBaseUrl}}/graphql

### User Logout
POST {{adminBaseUrl}}/api/profile/logout
Authorization: Bearer {{adminToken}}

### Get User Login Logs
GET {{adminBaseUrl}}/api/user/login-logs
Authorization: Bearer {{adminToken}}

### Get User Logout Logs
GET {{adminBaseUrl}}/api/user/logout-logs
Authorization: Bearer {{adminToken}}