### Member Login
POST {{adminBaseUrl}}/api/auth/login
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Get Member Profile
GET {{adminBaseUrl}}/api/profile/me
Authorization: Bearer {{adminToken}}

### Get List of Members
GET {{adminBaseUrl}}/graphql

### Member Logout
POST {{adminBaseUrl}}/api/profile/logout
Authorization: Bearer {{adminToken}}

### Get Member Login Logs
GET {{adminBaseUrl}}/api/member/get-login-logs
Authorization: Bearer {{adminToken}}

### Get Member Logout Logs
GET {{adminBaseUrl}}/api/member/get-logout-logs
Authorization: Bearer {{adminToken}}