### User Login/Register
POST {{userBaseUrl}}/api/auth/login
Content-Type: application/json

{
  "phone": "09123456789"
}

### Verify Phone and OTP
POST {{userBaseUrl}}/api/auth/verify
Content-Type: application/json

{
  "phone": "09123456789",
  "otp": "000000"
}

### Get User Profile
GET {{userBaseUrl}}/api/user/me
Authorization: Bearer {{userToken}}

### Update User Profile
PUT {{userBaseUrl}}/api/user/update
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "username": "test",
  "firstName": "John",
  "lastName": "Doe",
  "email": "test@gmail.com"
}

### Get Invoice by ID
GET {{userBaseUrl}}/api/invoice/get/0f2014a2-0752-4548-9166-afa1a8b1f55a
Authorization: Bearer {{userToken}}

### Get Invoice By Vehicle ID
GET {{userBaseUrl}}/api/invoice/get/vehicle/d8d31413-5e18-448d-8337-d5b5da9624e8
Authorization: Bearer {{userToken}}

### Get Invoice By Parking Lot
GET {{userBaseUrl}}/api/invoice/get/parking-lot/9772e5e5-3cca-4fa7-ad26-45823d638a4b
Authorization: Bearer {{userToken}}

### Create an Invoice
POST {{userBaseUrl}}/api/invoice/create/9772e5e5-3cca-4fa7-ad26-45823d638a4b/d8d31413-5e18-448d-8337-d5b5da9624e8
Authorization: Bearer {{userToken}}

### End an Invoice
POST {{userBaseUrl}}/api/invoice/end/9772e5e5-3cca-4fa7-ad26-45823d638a4b/0f2014a2-0752-4548-9166-afa1a8b1f55a
Authorization: Bearer {{userToken}}

### Pay an Invoice
POST {{userBaseUrl}}/api/invoice/pay/9772e5e5-3cca-4fa7-ad26-45823d638a4b/0f2014a2-0752-4548-9166-afa1a8b1f55a
Authorization: Bearer {{userToken}}

### Get Parking Lot by ID
GET {{userBaseUrl}}/api/parking-lot/get/9eac93b7-0b7e-4eb0-86d6-9c002fb4c8c1
Authorization: Bearer {{userToken}}

### Get Parking Lots By Range
GET {{userBaseUrl}}/api/parking-lot/get-by-location?latitude=7.110451&longitude=125.633836&distance=0.1
Authorization: Bearer {{userToken}}

### Get parking lots I manage
GET {{userBaseUrl}}/api/parking-lot/get-managing
Authorization: Bearer {{userToken}}

### Create Parking Lot
POST {{userBaseUrl}}/api/parking-lot/register
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "name": "Parking Lot 1",
  "latitude": 7.110451,
  "longitude": 125.633836,
  "address": "Address 1",
  "description": "Description 1",
  "capacity": 10
}

### Update Parking Lot
PUT {{userBaseUrl}}/api/parking-lot/update/2935523d-e3df-45f0-a211-c10f3ca5ff77
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "name": "Parking Lot 2",
  "latitude": 7.110451,
  "longitude": 125.633836,
  "address": "Address 2",
  "description": "Description 2",
  "capacity": 25
}

### Get My Vehicles
GET {{userBaseUrl}}/api/vehicle/get-my-vehicles
Authorization: Bearer {{userToken}}

### Get Vehicle by ID
GET {{userBaseUrl}}/api/vehicle/get/07b98e55-9ae5-49e4-9e2a-69bb6ed1497e
Authorization: Bearer {{userToken}}

### Vehicle Register
POST {{userBaseUrl}}/api/vehicle/register
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "name": "car",
  "plateNumber": "1234",
  "type": 0
}

### Update Vehicle
PUT {{userBaseUrl}}/api/vehicle/update/07b98e55-9ae5-49e4-9e2a-69bb6ed1497e
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "name": "motor",
  "plateNumber": "12345",
  "type": 1
}

### Add a user to a vehicle
PUT {{userBaseUrl}}/api/vehicle/add-user/07b98e55-9ae5-49e4-9e2a-69bb6ed1497e/cec4779b-7ecc-4602-a322-2633702a9ec8
Authorization: Bearer {{userToken}}

### Remove a user from a vehicle
PUT {{userBaseUrl}}/api/vehicle/remove-user/07b98e55-9ae5-49e4-9e2a-69bb6ed1497e/cec4779b-7ecc-4602-a322-2633702a9ec8
Authorization: Bearer {{userToken}}