### User Login/Register
POST {{address}}/api/auth/parking/login
Content-Type: application/json

{
  "phone": "09123456789"
}

### Verify Phone and OTP
POST {{address}}/api/auth/parking/verify
Content-Type: application/json

{
  "phone": "09123456789",
  "otp": "128255"
}