### Get Vehicles
GET {{address}}/api/vehicle/get
Authorization: Bearer {{token}}

### Vehicle Register
POST {{address}}/api/vehicle/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "car",
  "plateNumber": "1234",
  "type": 0
}

### Update Vehicle
PUT {{address}}/api/vehicle/update/877e08e3-f834-400b-969c-3d87056ec601
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "motor",
  "plateNumber": "12345",
  "type": 1
}