### Vehicle Register
POST {{address}}/api/vehicle/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "plateNumber": "1234"
}

### Get Vehicles
GET {{address}}/api/vehicle/get
Authorization: Bearer {{token}}