### Get Vehicles
GET {{address}}/api/vehicle/get
Authorization: Bearer {{token}}

### Vehicle Register
POST {{address}}/api/vehicle/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "plateNumber": "1234"
}

### Update Vehicle
PUT {{address}}/api/vehicle/update/0a6465d1-a716-4444-b032-aca483b1185d
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "plateNumber": "12345"
}