### User Login/Register
POST {{address-api}}/api/auth/login
Content-Type: application/json

{
  "phone": "09123456789"
}

### Verify Phone and OTP
POST {{address-api}}/api/auth/verify
Content-Type: application/json

{
  "phone": "09123456789",
  "otp": "000000"
}