### Get User Profile
GET {{address-api}}/api/user/me
Authorization: Bearer {{token}}

### Update User Profile
PUT {{address-api}}/api/user/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "test",
  "firstName": "John",
  "lastName": "Doe",
  "email": "test@gmail.com"
}