### Get My Vehicles
GET {{address-api}}/api/vehicle/get-my-vehicles
Authorization: Bearer {{token}}

### Get Vehicle by ID
GET {{address-api}}/api/vehicle/get/07b98e55-9ae5-49e4-9e2a-69bb6ed1497e
Authorization: Bearer {{token}}

### Vehicle Register
POST {{address-api}}/api/vehicle/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "car",
  "plateNumber": "1234",
  "type": 0
}

### Update Vehicle
PUT {{address-api}}/api/vehicle/update/07b98e55-9ae5-49e4-9e2a-69bb6ed1497e
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "motor",
  "plateNumber": "12345",
  "type": 1
}